### ISSUE TITLE
code block function doesn't work

### ISSUE THREAD

**Issue by mountain-geek** [klaussinani/tusk#95] opened 2018-07-05 19:27 UTC
Hello, 
I'm trying to type in some code inside on the notes and
code block(format) doesn't seem to function since I click it on the menu bar or using ctrl+shift+l

Thank you

**Comment by noamteyssier** [comment] 2018-08-20 22:13
Same here, Ubuntu 18.04

**Comment by nevgin** [comment] 2018-08-27 17:15
Same here, Ubuntu 18.04

**Comment by melihbildik** [comment] 2018-08-30 13:53
Same here, Mint 18

**Comment by Tomasz-Kluczkowski** [comment] 2018-09-14 15:37
And me , ubuntu 18.04

**Comment by batjko** [comment] 2018-09-25 07:59
Duplicate of #74

**Comment by jetacpp** [comment] 2018-09-28 06:56
Same here, is this Evernote issue or Tusk issue ?

**Comment by Chadwiki** [comment] 2018-10-03 00:08
Tusk 0.11.0 (x64) on Ubuntu 16.04

**Comment by klaussinani** [comment] 2018-12-15 19:44
Please follow https://github.com/klaussinani/tusk/issues/74 for updates.

**Closed by klaussinani** 2018-12-15 19:44 UTC
