### ISSUE TITLE
Theme toggle don't work on OSX

### ISSUE THREAD

**Issue by jadupl2** [klaussinani/tusk#164] opened 2019-02-15 16:00 UTC
**Describe the bug**
Theme toggle don't work on OSX.
Views, Toggle theme, what ever theme you choose nothing change,

**To Reproduce**
Views, Toggle theme

**Expected behavior**
Suppose to see the theme color to change

**Technical Info (please complete the following information)**
 - OS: High SIerra 10.13.6
 - Tusk Version: 0.21.0.622

**Comment by klaussinani** [comment] 2019-02-19 21:31
Please see #88 for more info

**Comment by livejamie** [comment] 2019-02-21 00:43
It seems to occur no matter which version of Evernote is being used.

**Comment by novdddd** [comment] 2019-03-03 18:06
@livejamie  Works fine on regular Evernote version

**Comment by klaussinani** [comment] 2019-03-03 18:10
Duplicate of #88

**Closed by klaussinani** 2019-03-03 18:10 UTC
Labels: duplicate
